### PR TITLE
feature/tslint/export

### PR DESCRIPTION
**Pull request by bonzzy**
prepared tslint for export

### CODE REVIEW

**Review by vilimco — APPROVED** [review]
Nista upitnoga. Approved.

**Comment by krukru** [comment]
It is beyond the scope of this PR, but I dislike that important configuration files are in docs/ folder (namely tslint.json). This should be extracted somewhere else. Also you can add 
``
        "variable-name": [
            "check-format",
            "allow-leading-underscore"
        ]
``
as the first custom rule

**Review by krukru — CHANGES_REQUESTED** [review]
Changes requested, see last comment

**Comment by bonzzy** [comment]
@krukru I added`"variable-name": [ "check-format", "allow-leading-underscore" ]`.
Can we merge this?

**Comment by krukru** [comment]
I still don't like that a configuration file that will be parsed is in the docs folder (/docs/typescript/tslint/tslint.json). Docs should contain non-executable files only

**Comment by bonzzy** [comment]
@krukru I changed path to standards/typescript/tslint/tslint.json

**Pull request merged**
