### PR TITLE
addition(rules): Add tslint rules and improve tsconfig

### PR DESCRIPTION
**Pull request by dvorsky**
# Summary
Added few rules for general best practices and naming conventions.
Also updated tsconfig to improve module resolution.

Mainly what I want to address is issues we had created and never resolved.
This includes: 
 - #22 - Enums must be PascalCase
 - #12 - Imports are absolute path with alias (eg: "../../../controlllers/AcmeController" becomes "@/controllers/AcmeController")
- #10 - it should be preferred to use template strings whenever possible (?)
 
I'm open for discussion for these rules

## Rules
- no-null
- no-any
- no-console - _false_
- prefer-template - prefer template string over concatenation
- max-line-length - 120 and ignore imports
- no-magic-numbers - assign numbers to variables for clarity about their values (general good practice)
- no-for-in-array - for...of loop should be used for arrays
- no-return-await - something I've seen in our codebases, its redundant
- prefer-object-spread - spread > Object.assign()
- unnecessary-else - warn about using "else" if you have early return
- naming convention:
  - enums/types/interfaces/classes - PascalCase
  - enum keys - PascalCase
  - general variables - camelCase
  - exported/global const variables - UPPER_CASE
  - exported const functions - camelCase
  - private/protected properties - _leadingUnderscore
  - public static const properties - UPPER_CASE
  - file-name-casing - PascalCase

### CODE REVIEW

**Comment by ilesar** [comment]
✅A very strict ruleset. I like it. 

⚠️Before I merge it, I would just like to clarify which types of projects will this be used for? Is this a general Typescript configuration which we will extend for other project types?

🧠I'm asking because libraries and frameworks could potentially have collisions with this set. For instance, Vue.js advises not to use underscores for any class property because it uses that convention internally. I actually stumbled upon a case where I had this collision.

**Comment by dvorsky** [comment]
@ilesar 

> Before I merge it, I would just like to clarify which types of projects will this be used for? Is this a general Typescript configuration which we will extend for other project types?

I thought we can try to use it everywhere, but if there are problems we can extract rules in "project-type" specific rule set.

>I'm asking because libraries and frameworks could potentially have collisions with this set. For instance, Vue.js advises not to use underscores for any class property because it uses that convention internally. I actually stumbled upon a case where I had this collision.

Underscore rule is a bit problematic, on one side, I don't like putting special prefix to indicate private property when typescript gives visibility options on its own (in JS you need underscore to indicate private since everything is actually public), but when making accessors you need to put underscore since signature can't be the same. So I thought its better to just put underscore everywhere and be done with this. But yeah, some languages/frameworks/services might be in conflict because of this. 

I think it would be alright to explicitly disable the rule in those projects (you can still override all these rules in your projects tslint files, these should be considered boilerplate and good starting point for ruleset so projects don't define rulesets without sharing them with other projects.

**Review by ilesar — COMMENTED** [review]
@Dvorsky @krukru @renatoruk 

I approve the merge of this pull request.

This merge is potentially going to affect a bunch of front-end projects. Since it's quite a strict ruleset, we need to have a backup plan for them. I would announce the update to the front-end team so they know to roll-back the package version if they will be overwhelmed by the rules.

There are currently 4 types of projects which could potentially have a need for a custom configuration:

- Vue front-end projects
- React front-end projects
- NodeJS projects
- Plain TS frontend projects

I think we currently have all four project types active. I would test the Vue and Node projects as soon as we publish the ruleset. @renatoruk Could test the React app, and we could give the plain TS front-end project to someone in the creative team.

**Comment by renatoruk** [comment]
I'm cool with this - I say we merge it. 
New projects will benefit from it, older probably not quite much. Even if we want to use it on older projects, we'll override the rules that are too much work.

**Comment by krukru** [comment]
Please rješite mi konflikte pa ćemo mergeati.

**Comment by renatoruk** [comment]
@krukru resolvao sam. Publishao bih, jedino razmišljam hoćemo li to pod minor ili major. Potencijalno je breaking za stare projekte pa bismo mogli major.

**Comment by krukru** [comment]
When in doubt, major!

**Pull request merged**
